
version: 2

sources: 
  - name: example
    database: valiant-surfer-411804
    schema: sol_data

    tables: 
      - name: 2022_sol_data
      - name: 2023_sol_data

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
